# Run to fix connection / nameserver issues when connected to VPN

vpn_on () {
    # Added a messy way to determine the script location without hard-coding a path
    SCRIPTPATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
    SCRIPTPATH=${SCRIPTPATH/"/c/"/'c:\\'}
    SCRIPTPATH=${SCRIPTPATH//'/'/'\\'}'\\vpnUpdateMetric.ps1'
    # Get the VPN adapter DNS server details and writes them to resolve conf
    # You can change the Cisco AnyConnect* string to change which adaptor it scans
    powershell.exe -Command 'Get-NetAdapter -InterfaceDescription "Cisco AnyConnect*" | Get-DnsClientServerAddress | Select -ExpandProperty ServerAddresses' | awk 'BEGIN { print "# Generated by vpn fix func on", strftime("%c"); print } { print "nameserver", $1 }' | tr -d '\r' | sudo tee /etc/resolv.conf

    # Forces the VPN interface metric to be higher than WSL so WSL can route
    powershell.exe -File ${SCRIPTPATH}
}

vpn_off () {
    # resets the resolv.conf to googles (set it to what you want to)
    wsl.exe -u root bash -c "echo nameserver 8.8.8.8 > /etc/resolv.conf"
}
